### PR TITLE
Revert "Refactoring rules and mail formatting"

### PR DESCRIPTION
**Pull request by maukoquiroga**
Reverts sgmap/betaGouvBot#80

### CODE REVIEW

**Comment by Morendil** [comment]
Another option is to merge #83, but you can take some time to review if you want. Mailer being broken shouldn't be a problem until june 15th :)

**Comment by maukoquiroga** [comment]
@Morendil Take a look at #86

**Comment by maukoquiroga** [comment]
@Morendil I propose you to merge #85 and #86, #83 goes in the same direction.

**Comment by Morendil** [comment]
Please help me out if I'm confused: intuitively if we are going to apply "Revert X" and then "X" where X is a previously merged PR, we might as well not merge either and just merge #83? The corrections applied for "entanglement" are not needed after #83.

**Comment by maukoquiroga** [comment]
@Morendil Closed #85, check for #86 as it's a refactoring by itself.

**Pull request closed without merging**
